version: '3'
services:
  mysql:
    image: mysql:8.0.34
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
     
    ports:
      - "3306:3306"
 networks:
      - backend-network
    command: 
       --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: /home/ubuntu/Online_Shopping_Mart/BE/Ecommerce-Backend  # Path to your Spring Boot app's Dockerfile directory
    image: spring
    container_name: spring
networks:
      - backend-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/osm?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin@123
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_SHOW-SQL: "true"
      SPRING_JPA_OPEN-IN-VIEW: "false"
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: DEBUG

    
    depends_on:
      - mysql


volumes:
  mysql-data:

networks:
  backend-network:
    driver: bridge
