version: '3'
services:
  frontend:
    build:
      context: /home/ubuntu/Online_Shopping_Mart/FE/ecommerce-frontend # Path to your React app's Dockerfile directory
    ports:
      - "3000:3000"

  backend:
    build:
      context: /home/ubuntu/Online_Shopping_Mart/BE/Ecommerce-Backend # Path to your Spring Boot app's Dockerfile directory
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/osm?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin@123
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_SHOW-SQL: "true"
      SPRING_JPA_OPEN-IN-VIEW: "false"
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: DEBUG
    ports:
      - "9096:9096"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.34
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
     
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
